server:
  port: 5000
spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 47.98.101.243
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    username: default
    password: YPCypc050717
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://yy-club-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1

        - id: auth
          uri: lb://yy-club-auth-dev
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: subject
          uri: lb://yy-club-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-32
  is-log: true
  token-prefix: jichi